# Generated by Django 4.2.6 on 2024-11-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user_vote_sum',
            field=models.FloatField(),
        ),
    ]
