# Generated by Django 4.2.16 on 2024-11-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_movie_poster_path_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='adult',
            field=models.CharField(max_length=50),
        ),
    ]
