# Generated by Django 4.2.16 on 2024-11-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
