# Generated by Django 4.2.16 on 2024-11-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_movies',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='articles.movie'),
        ),
    ]
